import type { Lang } from './native'

const en = {
  chat: 'Chat', models: 'Models', attach: 'Add a picture', camera: 'Camera', gallery: 'Gallery', removePhoto: 'Remove picture',
  photoTooLarge: 'Choose an image smaller than 20 MB.', photoInvalid: 'Choose an image file.', attachmentAlt: 'Attached picture',
  photoCaption: 'Checked on this phone', modelIntro: 'Manage the models stored on this phone.',
  languageModel: 'Language model', imageModel: 'Image model', knowledge: 'Knowledge base',
  languageHint: 'Understands text requests. Questions still work with keywords when this model is missing.',
  imageHint: 'Checks coffee-leaf pictures.', knowledgeHint: 'Saved advice, sources and market prices for chat requests.',
  installed: 'Installed', notInstalled: 'Not installed', loaded: 'Loaded', bundled: 'Included in app', preview: 'Preview',
  previewModel: 'Preview classifier', runtimeMissing: 'Language-model runtime is not included in this build.',
  loadModels: 'Load models', releaseModels: 'Release memory', importModel: 'Import model file', refresh: 'Refresh',
  modelImportHint: 'Choose Qwen3.5-0.8B-Q4_K_M.gguf from your phone’s files (about 533 MB).',
  modelReleaseHint: 'Releasing or importing turns off automatic SMS replies. Models load again with your next local question.',
  modelFailed: 'Couldn’t load the models. Check the installed file and available memory.',
  importFailed: 'Import failed. Check the filename, GGUF format and free storage.',
  modelStatusFailed: 'Couldn’t read model status.', modelWorking: 'Working…', modelImported: 'Model imported', modelReleased: 'Memory released', modelsLoaded: 'Models loaded',
  messages: 'Messages', photos: 'Photos', settings: 'Settings',
  chooseTitle: 'A little setup.\nThen you’re ready.', chooseIntro: 'Choose how you’ll use this phone. You can change this later in Settings.',
  phoneMode: 'Phone mode', basic: 'Basic phone', capable: 'Capable phone',
  basicHint: 'Send and receive SMS. Keep things light.', capableHint: 'SMS, photos and AI on this phone.',
  basicDetail: 'For a phone with less memory. The other phone handles the AI.', capableDetail: 'For the phone that runs the local models and helps other phones.',
  continue: 'Continue', memory: 'Phone memory', modeHint: 'Choose manually. Available memory and model size also matter.',
  sms: 'SMS', local: 'This phone', smsTitle: 'A little help,\na message away.',
  smsIntro: 'Send a question to the other phone. Its answer comes back by SMS.', localTitle: 'What’s on\nyour mind?',
  localIntro: 'Ask the models on this phone. Your questions stay here.',
  to: 'To', choosePhone: 'Choose a phone', addNumber: 'Add a phone number to start messaging.',
  edit: 'Edit', save: 'Save number', saved: 'Number saved', numberHint: 'Use the other phone’s number, including its country code.',
  invalidNumber: 'Enter a valid phone number with 7–15 digits.', numberPlaceholder: '+256 700 000 001',
  composer: 'Write a message…', askComposer: 'Ask a question…', send: 'Send SMS', ask: 'Ask this phone',
  smsNote: 'Uses your SIM, not internet. Carrier SMS charges apply.', localNote: 'Processed on this phone. No internet needed.',
  browser: 'Browser preview · SMS sending works in the Android app.', demo: 'Preview answer · not a real model result',
  permission: 'Allow SMS to send messages and see replies here.', allowSms: 'Allow SMS',
  sendFailed: 'Couldn’t send. Check your SIM, signal and SMS permissions.', denied: 'SMS permission is required. Your draft is still here.',
  unknown: 'Send status is unknown. Check your conversation before sending again.',
  sending: 'Sending…', sent: 'Sent', submitted: 'Submitted to carrier', failed: 'Not sent', received: 'Received', thinking: 'Looking into it…',
  noAnswer: 'No answer is available. Please ask an extension officer.',
  language: 'App language', phoneSettings: 'Your phone', contactSettings: 'SMS destination',
  modeHelp: 'Basic mode keeps photo tools and local AI off.',
  smsSetup: 'SMS access', granted: 'SMS is ready', notGranted: 'Permission needed',
  aiReplies: 'Automatic SMS replies', aiRepliesHint: 'Let this phone answer questions from the numbers below. Uses local models and carrier SMS.',
  helperOff: 'Off', helperOn: 'On', helperStarting: 'Starting…', noContacts: 'Add a number below before turning this on.',
  allowedPhones: 'Phones that can ask', name: 'Name', namePlaceholder: 'e.g. Mama', number: 'Phone number', add: 'Add phone', remove: 'Remove',
  duplicate: 'This phone number is already on the list.', replyLanguage: 'Reply language',
  tools: 'Farm tools', checkPrice: 'Check a buyer’s price', officer: 'Extension officer', officerHint: 'Used when sharing a finding with your officer.',
  storage: 'Message history', privacy: 'Saved on this phone. The newest 300 SMS messages are kept.',
  clear: 'Clear SMS history', clearConfirm: 'Delete all SMS history saved in Pandastic? This does not delete messages in your phone’s SMS app.',
  photoIntro: 'Take a picture or choose one from your gallery. The model checks it on this phone.', photoLocal: 'Pictures stay on this phone. They are not sent by SMS.',
  switchMode: 'Change phone mode', offline: 'No internet needed', availablePhones: 'Conversations', newNumber: 'Another phone',
  pendingSetup: 'Set up SMS in Settings to receive replies.', back: 'Back', priceTitle: 'Check a price',
}
const sw: typeof en = {
  chat: 'Mazungumzo', models: 'Modeli', attach: 'Ongeza picha', camera: 'Kamera', gallery: 'Picha zilizopo', removePhoto: 'Ondoa picha',
  photoTooLarge: 'Chagua picha ndogo kuliko MB 20.', photoInvalid: 'Chagua faili ya picha.', attachmentAlt: 'Picha iliyoambatishwa',
  photoCaption: 'Inakaguliwa kwenye simu hii', modelIntro: 'Dhibiti modeli zilizohifadhiwa kwenye simu hii.',
  languageModel: 'Modeli ya lugha', imageModel: 'Modeli ya picha', knowledge: 'Maarifa yaliyohifadhiwa',
  languageHint: 'Inaelewa maswali ya maandishi. Bila modeli hii, maswali bado hutumia maneno muhimu.',
  imageHint: 'Inakagua picha za majani ya kahawa.', knowledgeHint: 'Ushauri, vyanzo na bei za soko kwa maswali ya mazungumzo.',
  installed: 'Imewekwa', notInstalled: 'Haijawekwa', loaded: 'Imepakiwa', bundled: 'Ipo kwenye app', preview: 'Onyesho',
  previewModel: 'Modeli ya picha ya onyesho', runtimeMissing: 'Kiendeshi cha modeli ya lugha hakipo kwenye app hii.',
  loadModels: 'Pakia modeli', releaseModels: 'Achia kumbukumbu', importModel: 'Ingiza faili ya modeli', refresh: 'Sasisha',
  modelImportHint: 'Chagua Qwen3.5-0.8B-Q4_K_M.gguf kwenye faili za simu (takriban MB 533).',
  modelReleaseHint: 'Kuachia au kuingiza huzima majibu ya SMS yenyewe. Modeli zitapakiwa tena ukiuliza swali kwenye simu hii.',
  modelFailed: 'Modeli hazikupakiwa. Kagua faili na kumbukumbu iliyopo.',
  importFailed: 'Faili haikuingizwa. Kagua jina, aina ya GGUF na nafasi ya kuhifadhi.',
  modelStatusFailed: 'Hali ya modeli haipatikani.', modelWorking: 'Inafanya kazi…', modelImported: 'Modeli imeingizwa', modelReleased: 'Kumbukumbu imeachiwa', modelsLoaded: 'Modeli zimepakiwa',
  messages: 'Ujumbe', photos: 'Picha', settings: 'Mipangilio',
  chooseTitle: 'Chagua simu.\nKisha tuanze.', chooseIntro: 'Chagua matumizi ya simu hii. Unaweza kubadilisha baadaye kwenye Mipangilio.',
  phoneMode: 'Aina ya simu', basic: 'Simu ndogo', capable: 'Simu yenye uwezo',
  basicHint: 'Tuma na pokea SMS. Matumizi mepesi.', capableHint: 'SMS, picha na AI kwenye simu hii.',
  basicDetail: 'Kwa simu yenye kumbukumbu ndogo. Simu nyingine inaendesha AI.', capableDetail: 'Kwa simu inayoendesha modeli na kusaidia simu nyingine.',
  continue: 'Endelea', memory: 'Kumbukumbu ya simu', modeHint: 'Chagua mwenyewe. Kumbukumbu iliyopo na ukubwa wa modeli ni muhimu pia.',
  sms: 'SMS', local: 'Simu hii', smsTitle: 'Msaada upo,\ntuma ujumbe.',
  smsIntro: 'Tuma swali kwa simu nyingine. Jibu litarudi kwa SMS.', localTitle: 'Unataka\nkuuliza nini?',
  localIntro: 'Uliza modeli kwenye simu hii. Maswali yanabaki hapa.',
  to: 'Kwa', choosePhone: 'Chagua simu', addNumber: 'Weka namba ya simu ili kuanza.',
  edit: 'Badilisha', save: 'Hifadhi namba', saved: 'Namba imehifadhiwa', numberHint: 'Tumia namba ya simu nyingine pamoja na msimbo wa nchi.',
  invalidNumber: 'Weka namba sahihi yenye tarakimu 7–15.', numberPlaceholder: '+256 700 000 001',
  composer: 'Andika ujumbe…', askComposer: 'Uliza swali…', send: 'Tuma SMS', ask: 'Uliza simu hii',
  smsNote: 'Inatumia SIM, si intaneti. Gharama za SMS zinatumika.', localNote: 'Inachakatwa kwenye simu hii. Haihitaji intaneti.',
  browser: 'Onyesho la kivinjari · tuma SMS kwenye app ya Android.', demo: 'Jibu la onyesho · si matokeo ya modeli halisi',
  permission: 'Ruhusu SMS kutuma ujumbe na kuona majibu hapa.', allowSms: 'Ruhusu SMS',
  sendFailed: 'Haikutumwa. Kagua SIM, mtandao wa simu na ruhusa za SMS.', denied: 'Ruhusa ya SMS inahitajika. Ujumbe wako bado upo.',
  unknown: 'Hali ya kutuma haijulikani. Kagua mazungumzo kabla ya kutuma tena.',
  sending: 'Inatumwa…', sent: 'Imetumwa', submitted: 'Imewasilishwa kwa mtandao', failed: 'Haikutumwa', received: 'Imepokelewa', thinking: 'Ninaangalia…',
  noAnswer: 'Hakuna jibu kwa sasa. Tafadhali uliza afisa ugani.',
  language: 'Lugha ya app', phoneSettings: 'Simu yako', contactSettings: 'Simu ya kutumiwa SMS',
  modeHelp: 'Simu ndogo haitumii picha au AI kwenye simu hii.',
  smsSetup: 'Ruhusa ya SMS', granted: 'SMS iko tayari', notGranted: 'Ruhusa inahitajika',
  aiReplies: 'Majibu ya SMS yenyewe', aiRepliesHint: 'Simu hii ijibu maswali kutoka namba zilizo hapa chini. Inatumia modeli za ndani na SMS.',
  helperOff: 'Umezimwa', helperOn: 'Umewashwa', helperStarting: 'Inaanza…', noContacts: 'Ongeza namba hapa chini kabla ya kuwasha.',
  allowedPhones: 'Simu zinazoweza kuuliza', name: 'Jina', namePlaceholder: 'Mfano: Mama', number: 'Namba ya simu', add: 'Ongeza simu', remove: 'Ondoa',
  duplicate: 'Namba hii ipo tayari kwenye orodha.', replyLanguage: 'Lugha ya majibu',
  tools: 'Zana za shamba', checkPrice: 'Kagua bei ya mnunuzi', officer: 'Afisa ugani', officerHint: 'Inatumika kushiriki matokeo na afisa wako.',
  storage: 'Historia ya ujumbe', privacy: 'Imehifadhiwa kwenye simu hii. SMS 300 za karibuni zinabaki.',
  clear: 'Futa historia ya SMS', clearConfirm: 'Futa historia yote ya SMS kwenye Pandastic? Ujumbe kwenye app nyingine ya SMS hautafutwa.',
  photoIntro: 'Piga picha au chagua kwenye simu. Modeli inaikagua kwenye simu hii.', photoLocal: 'Picha zinabaki kwenye simu hii. Hazitumwi kwa SMS.',
  switchMode: 'Badilisha aina ya simu', offline: 'Haihitaji intaneti', availablePhones: 'Mazungumzo', newNumber: 'Simu nyingine',
  pendingSetup: 'Weka SMS kwenye Mipangilio ili kupokea majibu.', back: 'Rudi', priceTitle: 'Kagua bei',
}
export const ux: Record<Lang, typeof en> = { en, sw }
