"""Write ml/llm/slots.gbnf and ml/llm/slots.schema.json from one list of enums (contracts §4, §5).

The LLM (Qwen3.5-0.8B via llama.cpp) may only emit this one compact JSON object, keys in Slots order:
{"lang":..,"intent":..,"crop":..,"symptom":..,"commodity":..,"offer":..}
Symptoms are the condition suffixes of the classifier labels, so the model can only name a condition we know.

Usage: ml/.venv/Scripts/python ml/llm/make_grammar.py
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from leaf.config import P1_LABELS  # noqa: E402

LANGS = ["sw", "en"]
INTENTS = ["diagnose", "price", "planting", "help", "other"]
CROPS = ["coffee", "maize", "bean"]
SYMPTOMS = sorted({label.split("_", 1)[1] for label in P1_LABELS + ["maize_streak_virus", "maize_lethal_necrosis"]
                   if label != "other" and not label.endswith("_healthy")})
COMMODITIES = ["coffee_arabica_parchment", "coffee_arabica_drugar", "coffee_robusta_kiboko", "coffee_robusta_faq",
               "maize_grain", "beans_dry"]


def alternatives(values, nullable):
    options = [f'"\\"{v}\\""' for v in values] + (['"null"'] if nullable else [])
    return " | ".join(options)


def grammar() -> str:
    return "\n".join([
        "# Generated by ml/llm/make_grammar.py. Do not edit by hand.",
        "# One compact JSON object; keys in Slots order; enums only; offer = whole UGX per kg or null.",
        'root ::= "{\\"lang\\":" lang ",\\"intent\\":" intent ",\\"crop\\":" crop ",\\"symptom\\":" symptom '
        '",\\"commodity\\":" commodity ",\\"offer\\":" offer "}"',
        f"lang ::= {alternatives(LANGS, False)}",
        f"intent ::= {alternatives(INTENTS, False)}",
        f"crop ::= {alternatives(CROPS, True)}",
        f"symptom ::= {alternatives(SYMPTOMS, True)}",
        f"commodity ::= {alternatives(COMMODITIES, True)}",
        'offer ::= "null" | [1-9] [0-9]? [0-9]? [0-9]? [0-9]? [0-9]? [0-9]?',
        "",
    ])


def schema() -> dict:
    nullable = lambda values: {"enum": values + [None]}
    return {
        "type": "object", "additionalProperties": False,
        "required": ["lang", "intent", "crop", "symptom", "commodity", "offer"],
        "properties": {
            "lang": {"enum": LANGS}, "intent": {"enum": INTENTS}, "crop": nullable(CROPS),
            "symptom": nullable(SYMPTOMS), "commodity": nullable(COMMODITIES),
            "offer": {"type": ["integer", "null"], "minimum": 1, "maximum": 9999999},
        },
    }


if __name__ == "__main__":
    (HERE / "slots.gbnf").write_text(grammar(), encoding="utf-8")
    (HERE / "slots.schema.json").write_text(json.dumps(schema(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote slots.gbnf + slots.schema.json; symptoms: {SYMPTOMS}")
